### ISSUE TITLE
Doppeltes id-Attribut

### ISSUE THREAD

**Issue by bernharduw** [cmatschiner/mundschank-forum#10]
https://github.com/cmatschiner/mundschank-forum/blob/51c4a026f63aab36a6a880718fac5225e55e74a7/index.html#L201

Du brauchst hier nur ein ID-Attribut, und das auch nur, wenn du auf den Block verlinken willst oder den Block explizit über die id stylest.

**Comment by cmatschiner** [comment]
Doppelter ID - übersehen. Einen brauche ich als Anchor.  Behoben ;)
