### ISSUE TITLE
Container in Container

### ISSUE THREAD

**Issue by bernharduw** [cmatschiner/mundschank-forum#11]
https://github.com/cmatschiner/mundschank-forum/blob/51c4a026f63aab36a6a880718fac5225e55e74a7/index.html#L233

Hier bist du bereits in einem Container. Ich nehme an, du wolltest den vorigen Container schließen und dann einen neuen aufmachen.

Das führt dazu, dass der Container doppeltes Padding hat.

**Comment by cmatschiner** [comment]
Verstehe ich nicht. Voherigen Container habe ich geschlossen. Doppeltes Padding sehe ich nicht. Old Issue?

**Comment by bernharduw** [comment]
![image](https://user-images.githubusercontent.com/740978/48935106-bcbac880-ef06-11e8-820a-2a8411296c8f.png)

Mir ist es aufgefallen, weil der letzte Block weiter eingerückt ist als der Footer. 
Sowohl der container strip-quote text-center in schwarz als auch der container about sitzen in einem übergeordneten Container, deswegen sind die inneren Container nur 1110px breit statt 1140px (im xl-Breakpoint).

Sobald es korrekt ist, müssten "Kontaktieren Sie uns" in der letzten Zeile des main-Inhalts und "Copyright 2018 …" vertikal gleich ausgerichtet sein.

**Comment by cmatschiner** [comment]
Nicht der einzige <div> zu viel lt. https://validator.w3.org 👍
