### ISSUE TITLE
Verbesserung: Nur abweichende Klassen definieren

### ISSUE THREAD

**Issue by bernharduw** [cmatschiner/mundschank-forum#12]
https://github.com/cmatschiner/mundschank-forum/blob/51c4a026f63aab36a6a880718fac5225e55e74a7/index.html#L235

In Bootstrap sind responsive classes immer auch in den übergeordneten Breakpoints wirksam. Du musst z.B. nicht col-sm-4 und col-lg-4 definieren, es reicht col-sm-4.

Du könntest hier beispielsweise folgendes schreiben, das reicht aus:
````html
<div class="col-12 col-lg-6 px-4 quote-all"> 
````

**Comment by cmatschiner** [comment]
Das ist parktisch! Muss ich überlesen haben.
