### ISSUE TITLE
HTML / Bootstrap: navbar – justify-content-end

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#13]
https://github.com/cmatschiner/mundschank-forum/blob/14a1fa1442b02b5e6cf6d4d6c77d61d233a114f5/index.html#L58

"Immediate children elements in .navbar use flex layout and will default to justify-content: between." (getbootstrap.com) Nur bei mir funktioniert's nicht so... Die Nav-Links kleben rechts am Logo. Jegliche Versuche letztere mit zB. justify-content-end rechtsbündig anzuordnen klappen nicht.

**Comment by bernharduw** [comment]
Eigentlich ist ul kein "immediate child" von navbar, sondern navbar-collapse ist das. Es funktioniert trotzdem (auch ohne justify-content), nur hast du die falsche Klasse bei der &lt;ul> gesetzt: mr-auto macht den rechten Rand breit, du wolltest vermutlich ml-auto für den linken Rand. Dann würde es passen.

Im Zweifelsfall schau dir in den Chrome DevToops an, wo jetzt genau die margins angezeigt werden, man sieht das dort ganz gut:

![image](https://user-images.githubusercontent.com/740978/49138402-5a3f3f00-f2ef-11e8-96ba-dcb306f6474a.png)

**Comment by cmatschiner** [comment]
Wenn man vor lauter Bäumen den Wald nicht mehr sieht... ;)
