### ISSUE TITLE
HTML / Bootstrap: navbar - active attribute

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#14]
https://github.com/cmatschiner/mundschank-forum/blob/14a1fa1442b02b5e6cf6d4d6c77d61d233a114f5/index.html#L60

Warum den Link "active" setzten? Dieser wird nur permanent (nicht sinnvoll) fett dargestellt. Wozu?

**Comment by bernharduw** [comment]
Das ist für Unterseiten gedacht, oder du setzt die Klasse dynamisch per Javascript.

**Comment by cmatschiner** [comment]
Dachte ich mir schon. Es wird Zeit, dass ich endlich mit Java Script loslege. Merke schon, dass sich vieles einfach nicht mehr mit HTML/CSS umsetzen lässt.
