### ISSUE TITLE
HTML / Bootstrap: navbar – span element

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#15]
https://github.com/cmatschiner/mundschank-forum/blob/14a1fa1442b02b5e6cf6d4d6c77d61d233a114f5/index.html#L62

Warum das <span> Element? Die "sr-only" Klasse habe ich bereits mehrfach eingesetzt, hier verstehe ich den Einsatz nicht wirklich...

**Comment by bernharduw** [comment]
"Screen reader only", das ist für die Barrierefreiheit notwendig. Dann liest der Screenreader vor, auf welcher Seite du bist. Auf deutsch müsstest du "(aktuelle Seite)" oder so hinschreiben, aber da das bei dieser Website ohnehin nicht funktionieren würde, lass es weg.

**Comment by cmatschiner** [comment]
Alles klar
