### ISSUE TITLE
CSS / Bootstrap: navbar – modify bootstrap's default design

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#16]
https://github.com/cmatschiner/mundschank-forum/blob/14a1fa1442b02b5e6cf6d4d6c77d61d233a114f5/styles/style.css#L86-87

Ich nehme an, ich kann die Default-Bootstrap-Designvorgaben für die navbar nur im Bootstrap-Style-Sheet abändern, oder?

**Comment by bernharduw** [comment]
Nein, Bootstrap ist eigentlich fürs Customizing gedacht.

Vielleicht ist in diesem Fall ein spezifischer Selector besser, etwa `.nav-link` oder `.nav-item` oder ein allgemeiner wie `.links-nav` oder auch `#bar-main`. Kommt darauf an, was du machen möchtest. Wenn wirklich alles in der Navbar größer sein soll, nur die Links kleiner, dann spezifisch auf .nav-link, aber vermutlich willst du die Schrift in der gesamten #bar-main ändern, dann würde ich das auch so machen.

**Comment by cmatschiner** [comment]
Erledigt: habe .bar-main sowie die BS-Klasse .navbar-link verwendet
