### ISSUE TITLE
HTML: Anführungszeichen des Zitats auf nächster Zeile obwohl Zeilenumbruch <br> nach InLine Element <q> 

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#2]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/index.html#L117

**Comment by cmatschiner** [comment]
Das Anführungszeichen des Zitats wird in der nächsten Zeile abgebildet obwohl ich den Zeilenumbruch <br> nach dem In-Line-Element <q> gesetzt habe. Ist die Verwendung von <br> okay? Mir ist keine andere Möglichkeit eingefallen nachdem.

**Comment by bernharduw** [comment]
Du hast den span-Tag davor als "display:block" definiert, deswegen ist der span ein eigener Block, der dem nachfolgenden Anführungszeichen keinen Platz lässt.

Ein besser geeigneter Tag ist &lt;blockquote>, der setzt das ganze Zitat in einen Block. Innerhalb des Blockquote-Blocks kannst du dann auch mehrere &lt;p>-Absätze machen und den Namen als "Autor" markieren, entweder mit &lt;address> oder &lt;cite>.

**Comment by cmatschiner** [comment]
Alles klar
