### ISSUE TITLE
CSS: Aufhebung Bootstrap Padding-Voreinstellungen

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#3]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/styles/style.css#L20-L26

Legitime bzw. best-practice Methode um Bootstrap Padding-Einstellungen aufzuheben?

**Comment by bernharduw** [comment]
👍
