### ISSUE TITLE
CSS: .flex für Non-Bootstrap-container

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#4]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/styles/style.css#L34-L36

Habe eine eigene Klasse "flex" für Non-Bootstrap-container definiert. Okay?

**Comment by bernharduw** [comment]
ja, warum nicht!
