### ISSUE TITLE
CSS: Zentrierung eines oversized Images innerhalb eines Containers

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#5]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/styles/style.css#L349

Sobald ich das Bild innerhalb des col-4 über 100% vergrößere, ist es nicht mehr mittig / auf Achse sondern seitlich versetzt. Object-position: center bewirkt nichts. Was übersehe ich hier?

**Comment by bernharduw** [comment]
Du zentrierst mit `text-align: center;` – das wirkt nur bei Inline-Elementen, die kleiner sind als das Parent-Element. Wenn du dem Bild eine Breite von z.B. 150% geben willst, kannst du das Bild mit `margin-left: -25%;` nach links schieben:

- 100% breit ist der Container, 150% das Bild.
- 150% - 100% = 50%.
- Also steht das Bild links und rechts je 25% in den Container daneben.
- Um genau zu sein, könntest du margin-left und margin-right jeweils auf -25% setzen, aber rechts ist nicht unbedingt notwendig, weil das Bild ohnehin automatisch drübersteht, wenn nicht genug Platz ist.

**Comment by cmatschiner** [comment]
Thx!
