### ISSUE TITLE
CSS: Fixierung des Headers verändert Container-Breite 

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#6]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/styles/style.css#L110

Sobald ich die Position-Property auf "fixed" setze, verringert sich sich die Containerbreite auf ca. 930px. Warum?

**Comment by bernharduw** [comment]
`position: fixed;` und `position: absolute;` verhalten sich da gleich: Das Element erhält einfach seine "natürliche" Breite, es ist dann so breit wie sein Inhalt, weil du es aus dem normalen content-flow herausnimmst. Du kannst aber mit `width: 100%;` die Breite wieder anpassen. Oder alternativ auch `left: 0; right: 0;`, dann positionierst du den linken Rand des Elements ganz links und den rechten Rand ganz rechts, damit ist die width dann die gesamte Breite.

**Comment by cmatschiner** [comment]
Alles klar.
