### ISSUE TITLE
CSS: Highlight active / current link in header

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#7]
https://github.com/cmatschiner/mundschank-forum/blob/821a84012a7ccbb6f3a2896d1b8b3e0d02dbef53/styles/style.css#L185-L186

Ich möchte, dass je nach der aktuellen Scroll-Position der entsprechende Link in der Navigationsleiste farblich hervorgehoben wird. Mit "active" gelingt es mir nicht.

**Comment by bernharduw** [comment]
Das geht mit CSS nicht, da musst du Javascript einsetzen. :hover betrifft das Element, wenn du mit der Maus drüberfährst, und :active ist der Zustand, wenn du gerade draufklickst oder mit mit dem Finger drauftippst.

**Comment by cmatschiner** [comment]
Dachte ich mir schon ....
