### ISSUE TITLE
Bootstrap issue

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#8]
https://github.com/cmatschiner/mundschank-forum/blob/51c4a026f63aab36a6a880718fac5225e55e74a7/index.html#L32

Bootstrap Klasse "position-sticky" funktioniert nicht mehr. Anfänglich schon... Keine Ahnung was los ist.

**Comment by bernharduw** [comment]
`position: sticky;` ist ein sehr spezielles CSS-Feature: Das Child-Element (auf das du sticky anwendest) wird innerhalb des Parent-Elements fix auf der Seite positioniert, aber sobald das Parent-Element aus dem sichtbaren Bereich wandert, geht auch das Child-Element mit. Du hast einen container-fluid herumgelegt, der nur so groß ist wie der Header, deswegen funktioniert das nicht.

Eine gute Erklärung findest du auf [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning#position_sticky), außerdem einen typischen Anwendungsfall: Das letzte Beispiel auf der Seite zeigt eine Liste von Wörtern, getrennt durch Zwischenüberschriften für die Anfangsbuchstaben.

Ich habe vor einiger Zeit ein wenig an meiner eigenen Website gearbeitet, da habe ich das Feature für die Zwischenüberschriften auf einer Unterseite verwendet: https://develop--bernhard-gschwantner.netlify.com/projects/landhaus-altlengbach - ist noch arges Work in Progress, aber für sowas ist das sinnvoll. Bei einem Website-Header eher nicht so.

**Comment by cmatschiner** [comment]
position: sticky ist noch ein Buch mit sieben Siegeln, zumal ich die Parent-Child Abhängigkeit noch wenig verstehe. Deine Website veranschaulicht prima letzteres. Thx
