### ISSUE TITLE
Bootstrap issue / justify-content-...

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/mundschank-forum#9]
https://github.com/cmatschiner/mundschank-forum/blob/51c4a026f63aab36a6a880718fac5225e55e74a7/index.html#L292

Bootstrap-Klasse "justify-content-...." funktioniert nicht. Footer werde ich noch komplett ändern (responsive), möchte aber gerne verstehen woran es liegt.

**Comment by bernharduw** [comment]
Da verstehe ich nicht, was du erreichen möchtest. Innerhalb der Row hast du eine col-4 und eine col-8, da bleibt ja kein Platz für justify-content mehr. Hättest du zwei col-4, dann hätte das einen Effekt, schaut aber komisch aus.

Im übergeordneten container überschreibst du übrigens (meiner Meinung nach unabsichtlich) das horizontale Padding (von 15px auf 16px) - die Klasse `px-3`ist unnötig.

**Comment by cmatschiner** [comment]
Thx. Hab Inhalt und Kontainer verwechselt. Inhalt des rechten Kontainers rechtsbündig :)
